// PARITY check of the LibTorch backend against PyTorch.
//
// It is the make-or-break test of the C++ engine: without it the engine could
// run very fast and play in a subtly different way without anyone noticing. Run
// it on the machine with LibTorch BEFORE using the engine to produce results.
//
//   1) python engine_c/tools/export_jit.py weights/champion.pt model_jit.pt cuda
//   2) ./engine_c/build/parity_check model_jit.pt cuda
//
// The device of step 1 must be the one of step 2: a reference computed on the
// CPU differs from CUDA by ~1e-3 without any error (see export_jit.py).
//
// It reads the test input and the reference output generated by the Python
// script, passes them to the LibTorch backend and compares.
#include "libtorch_backend.hpp"
#include "encoder.hpp"
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <algorithm>    // std::max
#include <string>
#include <vector>

using namespace dama;

static std::vector<float> read_floats(const std::string& path) {
    FILE* f = std::fopen(path.c_str(), "rb");
    if (!f) { printf("cannot open %s\n", path.c_str()); std::exit(2); }
    std::fseek(f, 0, SEEK_END);
    long bytes = std::ftell(f);
    std::fseek(f, 0, SEEK_SET);
    std::vector<float> v(bytes / sizeof(float));
    size_t got = std::fread(v.data(), sizeof(float), v.size(), f);
    std::fclose(f);
    if (got != v.size()) { printf("incomplete read of %s\n", path.c_str()); std::exit(2); }
    return v;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        printf("usage: parity_check <model_jit.pt> [cpu|cuda] [tolerance]\n");
        return 2;
    }
    std::string model = argv[1];
    std::string device = (argc > 2) ? argv[2] : "cpu";
    double tol = (argc > 3) ? std::atof(argv[3]) : 1e-4;

    auto input = read_floats(model + ".input");
    auto ref = read_floats(model + ".ref");

    const int P = ENC_IN_PLANES * 8 * 8;
    if (input.size() % P != 0) {
        printf("input of unexpected size (%zu, not a multiple of %d)\n", input.size(), P);
        return 2;
    }
    int n = (int)(input.size() / P);
    size_t expect_ref = (size_t)n * ENC_POLICY_SIZE + (size_t)n;
    if (ref.size() != expect_ref) {
        printf("reference of unexpected size (%zu, expected %zu)\n",
               ref.size(), expect_ref);
        return 2;
    }
    printf("parity_check: model=%s device=%s B=%d tolerance=%.1e\n",
           model.c_str(), device.c_str(), n, tol);

    std::vector<float> logits((size_t)n * ENC_POLICY_SIZE), values((size_t)n);
    try {
        // STRICT fp32 for the comparison: with TF32 on, the two sides can
        // differ by ~1e-3 on the logits from arithmetic alone, and that noise
        // hides the real question (do they compute the same thing?). The Python
        // reference is generated with the same setting by
        // engine_c/tools/export_jit.py.
        set_tf32(false);
        LibTorchBackend backend(model, device);
        backend.forward(input.data(), n, logits.data(), values.data());
    } catch (const std::exception& e) {
        printf("backend error: %s\n", e.what());
        return 1;
    }

    // --- raw differences, with THEIR SCALE ------------------------------
    // A verdict based only on |diff| of the logits against a fixed threshold
    // would be wrong: logits are UNBOUNDED, values live in [-1,1], and the same
    // absolute tolerance on both measures two different things. So the scale
    // and the relative error are reported too.
    double max_logit_diff = 0.0, max_value_diff = 0.0, logit_scale = 0.0;
    for (size_t i = 0; i < logits.size(); i++) {
        max_logit_diff = std::max(max_logit_diff,
                                  (double)std::fabs(logits[i] - ref[i]));
        logit_scale = std::max(logit_scale, (double)std::fabs(ref[i]));
    }
    for (int i = 0; i < n; i++)
        max_value_diff = std::max(max_value_diff,
            (double)std::fabs(values[i] - ref[logits.size() + i]));
    double rel_logit = max_logit_diff / std::max(1.0, logit_scale);

    // --- what REALLY determines the engine's behavior ---------------------
    // The MCTS does not use the raw logits: it uses the PROBABILITIES derived
    // from them (softmax) and the value. A difference of 3e-3 on a logit of
    // magnitude 8 does not visibly move the distribution; a difference in the
    // probabilities instead changes which moves get explored. This is the
    // comparison that decides whether the engine PLAYS the same way.
    //
    // NOTE: it stays a strict criterion for real bugs. A wrong memory layout,
    // swapped weights or a wrong forward pass produce probability differences
    // of order 0.1-1, i.e. thousands of times the threshold.
    double max_prob_diff = 0.0;
    for (int b = 0; b < n; b++) {
        const float* a = logits.data() + (size_t)b * ENC_POLICY_SIZE;
        const float* r = ref.data() + (size_t)b * ENC_POLICY_SIZE;
        double ma = -1e30, mr = -1e30;
        for (int k = 0; k < ENC_POLICY_SIZE; k++) {
            ma = std::max(ma, (double)a[k]);
            mr = std::max(mr, (double)r[k]);
        }
        double sa = 0.0, sr = 0.0;
        std::vector<double> pa(ENC_POLICY_SIZE), pr(ENC_POLICY_SIZE);
        for (int k = 0; k < ENC_POLICY_SIZE; k++) {
            pa[k] = std::exp((double)a[k] - ma); sa += pa[k];
            pr[k] = std::exp((double)r[k] - mr); sr += pr[k];
        }
        for (int k = 0; k < ENC_POLICY_SIZE; k++)
            max_prob_diff = std::max(max_prob_diff,
                                     std::fabs(pa[k] / sa - pr[k] / sr));
    }

    // --- negative control: does the criterion discriminate? --------------
    // The reference is compared with a DELIBERATELY wrong version of itself
    // (logits in reversed order, as a wrong memory layout would give). If the
    // threshold did not reject even this, the test would be vacuous and
    // "PARITY OK" would mean nothing.
    double sabotage_diff = 0.0;
    {
        const float* r = ref.data();
        double mr = -1e30;
        for (int k = 0; k < ENC_POLICY_SIZE; k++) mr = std::max(mr, (double)r[k]);
        std::vector<double> pr(ENC_POLICY_SIZE), ps(ENC_POLICY_SIZE);
        double sr = 0.0, ss = 0.0;
        for (int k = 0; k < ENC_POLICY_SIZE; k++) {
            pr[k] = std::exp((double)r[k] - mr); sr += pr[k];
            ps[k] = std::exp((double)r[ENC_POLICY_SIZE - 1 - k] - mr); ss += ps[k];
        }
        for (int k = 0; k < ENC_POLICY_SIZE; k++)
            sabotage_diff = std::max(sabotage_diff,
                                     std::fabs(pr[k] / sr - ps[k] / ss));
    }

    printf("  logit : max |diff| = %.3e   (scale max |ref| = %.2f, "
           "relative = %.3e)\n", max_logit_diff, logit_scale, rel_logit);
    printf("  policy: max PROBABILITY |diff| = %.3e   <-- decides the play\n",
           max_prob_diff);
    printf("  value : max |diff| = %.3e\n", max_value_diff);
    printf("  [negative control] a WRONG output would give %.3e, "
           "i.e. %.0fx the threshold\n", sabotage_diff, sabotage_diff / tol);

    bool ok = (max_prob_diff < tol) && (max_value_diff < tol);
    printf("\n%s\n", ok
        ? "PARITY OK: the C++ backend produces the same probabilities and\n"
          "the same values as PyTorch: the engine plays identically."
        : "PARITY FAILED: do NOT use the engine to produce results until it is green.");
    if (ok && rel_logit > 1e-4)
        printf("(logits slightly different in absolute value: reduced-precision\n"
               " arithmetic on the GPU, irrelevant after the softmax.)\n");
    return ok ? 0 : 1;
}
